// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kicpepyarfiorraejwqh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtpY3BlcHlhcmZpb3JyYWVqd3FoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMzYxOTUsImV4cCI6MjA2NjcxMjE5NX0.HVotvhHkzczJEB359s92MQTV9TD9okl6CGnctghAUvo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);